### ISSUE TITLE
[0.10.0] ReferenceError: DOMRect is not defined in Fastboot

### ISSUE THREAD

**Issue by lucacorti** [ember-animation/ember-animated#189]
When running ember-animated 0.10.0 in fastboot:

```There was an error running your app in fastboot. More info about the error: 
 ReferenceError: DOMRect is not defined
    at Module.callback (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-animated/-private/bounds.js:69:1)
    at Module.exports (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:106:1)
    at Module._reify (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:104:1)
    at Module._reify (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:104:1)
    at Module._reify (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:143:1)
    at Module.reify (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:130:1)
    at Module.exports (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:104:1)
    at requireModule (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/vendor/loader/loader.js:27:1)
    at Class._extractDefaultExport (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:432:1)
    at Class.resolveOther (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:103:1)
    at Class.resolve (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:163:1)
    at resolve (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container/index.js:1200:1)
    at Registry.resolve (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container/index.js:740:1)
    at Registry.resolve (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container/index.js:743:1)
    at factoryFor (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container/index.js:300:1)
    at Container.factoryFor (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/container/index.js:215:1)
    at Class.factoryFor (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:131:1)
    at componentFor (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:9970:1)
    at lookupComponentPair (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:9979:1)
    at lookupComponent (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:10013:1)
    at RuntimeResolver._lookupComponentDefinition (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:10240:1)
    at RuntimeResolver.lookupComponentHandle (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:10084:1)
    at CompileTimeLookup.lookupComponentDefinition (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:6480:1)
    at LazyCompiler.resolveLayoutForTag (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/opcode-compiler.js:960:1)
    at /var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/opcode-compiler.js:130:1
    at Compilers.compile (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/opcode-compiler.js:44:1)
    at compile (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/opcode-compiler.js:740:1)
    at LazyCompiler.add (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/opcode-compiler.js:934:1)
    at CompilableBlock.compile (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/opcode-compiler.js:729:1)
    at Object.evaluate (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:721:1)
    at AppendOpcodes.evaluate (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:73:1)
    at LowLevelVM.evaluateSyscall (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:3295:1)
    at LowLevelVM.evaluateInner (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:3241:1)
    at LowLevelVM.evaluateOuter (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:3233:1)
    at VM.next (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:5299:1)
    at TemplateIteratorImpl.next (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@glimmer/runtime.js:5335:1)
    at RootState.render (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5649:1)
    at TransactionRunner.runInTransaction (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:2109:1)
    at runInTransaction (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/metal/index.js:2238:1)
    at InertRenderer._renderRoots (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5946:1)
    at InertRenderer._renderRootsTransaction (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5984:1)
    at InertRenderer._renderRoot (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5903:1)
    at InertRenderer._appendDefinition (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5818:1)
    at InertRenderer.appendOutletView (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/@ember/-internals/glimmer/index.js:5804:1)
    at invokeWithOnError (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:349:1)
    at Queue.flush (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:229:1)
    at DeferredActionQueues.flush (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:426:1)
    at Backburner._end (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:960:1)
    at Backburner._boundAutorunEnd (/var/folders/f7/4l5jd79d4zd4pf_rym3xbyzw0000gn/T/broccoli-89630W4voHOm7hy74/out-406-broccoli_persistent_filter_autoprefixer_filter/assets/backburner.js:629:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

This is on ember 3.14.3 and ember-cli-fastboot 2.2.1, works fine with 0.9.0

**Comment by knownasilya** [comment]
Seeing the same issue.

**Comment by rwwagner90** [comment]
Hitting this as well. Any workarounds? I see there is a draft PR.

**Comment by ef4** [comment]
You can do this same polyfill in your own app:

https://github.com/ember-animation/ember-animated/pull/192/commits/0fdec3f9e389f7886354a84cc1ce87efdf5e29f1

That PR got stuck on proper test coverage.

**Comment by rwwagner90** [comment]
@ef4 what tests need to be written? Is it not just shipping the polyfill?

**Comment by ef4** [comment]
All I meant is that when I last had time to work on this I tried to also add test coverage so we don't regress by breaking fastboot like this again.

But I agree we can ship without test coverage if somebody else wants to pick up that work and make a smaller PR with just the polyfill, before I get around to it.

**Comment by rwwagner90** [comment]
Ah, gotcha. I may take a look into it, if no one else does first.

**Comment by SergeAstapov** [comment]
> But I agree we can ship without test coverage if somebody else wants to pick up that work and make a smaller PR with just the polyfill, before I get around to it.

@rwwagner90 @ef4 did so in #204.
@ef4 do you still think this can be merged and new version released?

**Comment by rwwagner90** [comment]
@ef4 could we get that PR merged, and a new version released please?

**Comment by ef4** [comment]
I merged the PR, but that PR doesn't actually fix fastboot as far as I can tell.

There is no `window` in fastboot.

**Comment by SergeAstapov** [comment]
> There is no `window` in fastboot.

@ef4 did you mean just presence of `window` object or an implementation of Window WEB API interface?
Asking because `fastboot` library provides `window` object with some props in https://github.com/ember-fastboot/fastboot/blob/master/src/sandbox.js#L35

**Comment by ef4** [comment]
Oh ok good, so maybe I am wrong and this does fix fastboot.

(That kind of question in general is why my original PR was also trying to add CI coverage for fastboot, I don't like not having tests as the final arbiter.)

**Comment by rwwagner90** [comment]
@SergeAstapov have you tested it in Fastboot?

**Comment by SergeAstapov** [comment]
@rwwagner90 sorry for delay here. We have this fix up and running in prod and haven't had any issues.
Unless I'm missing anything and would love to look further then.

**Comment by lucacorti** [comment]
@ef4 works for me in fastboot since
