### ISSUE TITLE
Attempted to resolve -element, which was expected to be a helper, but nothing was found

### ISSUE THREAD

**Issue by wagenet** [ember-animation/ember-animated#450]
This seems like it may be connected to https://github.com/tildeio/ember-element-helper/pull/82/files

**Comment by wagenet** [comment]
This can be fixed by locking to ember-element-helper 0.6.0.

**Comment by gwak** [comment]
@SergeAstapov @ef4 I'm still seeing this error using:

-  `ember-animated@1.0.4`
- `ember-element-helper@0.6.1`
- `broccoli-builder@3.5.2`
- `node@v14.18.2`

```bash
Module build failed (from ../../../../../../../../Users/cwanty/dev/volta/client/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 8)
$TMPDIR/embroider/ae5ed8/node_modules/ember-animated/dist/components/animated-container.js/animated-container.js: Missing helper: -element in node_modules/ember-animated/dist/components/animated-container.js
    at PoolWorker.fromErrorObj (/Users/cwanty/dev/volta/client/node_modules/thread-loader/dist/WorkerPool.js:346:12)
    at /Users/cwanty/dev/volta/client/node_modules/thread-loader/dist/WorkerPool.js:219:29
    at mapSeries (/Users/cwanty/dev/volta/client/node_modules/neo-async/async.js:3625:14)
    at CompatResolver.dependenciesOf (/Users/cwanty/dev/volta/client/node_modules/@embroider/compat/src/resolver.js:252:33)
    at NodeTemplateCompiler.precompile (/Users/cwanty/dev/volta/client/node_modules/@embroider/core/src/template-compiler-common.js:61:42)
    at precompile (/Users/cwanty/dev/volta/client/node_modules/@embroider/core/src/babel-plugin-inline-hbs-deps.js:23:61)
    at insertCompiledTemplate (/Users/cwanty/dev/volta/client/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:50:42)
    at PluginPass.CallExpression (/Users/cwanty/dev/volta/client/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:142:21)
    at newFn (/Users/cwanty/dev/volta/client/node_modules/@babel/traverse/lib/visitors.js:177:21)
    at NodePath._call (/Users/cwanty/dev/volta/client/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/cwanty/dev/volta/client/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/cwanty/dev/volta/client/node_modules/@babel/traverse/lib/path/context.js:100:31)
    at TraversalContext.visitQueue (/Users/cwanty/dev/volta/client/node_modules/@babel/traverse/lib/context.js:105:16)
```

**Comment by ztjohns** [comment]
> @SergeAstapov @ef4 I'm still seeing this error using:
> 
> * `ember-animated@1.0.4`
> * `ember-element-helper@0.6.1`
> * `broccoli-builder@3.5.2`
> * `node@v14.18.2`
> 
> ```shell
> Module build failed (from ../../../../../../../../Users/cwanty/dev/volta/client/node_modules/thread-loader/dist/cjs.js):
> Thread Loader (Worker 8)
> $TMPDIR/embroider/ae5ed8/node_modules/ember-animated/dist/components/animated-container.js/animated-container.js: Missing helper: -element in node_modules/ember-animated/dist/components/animated-container.js
>     at PoolWorker.fromErrorObj (/Users/cwanty/dev/volta/client/node_modules/thread-loader/dist/WorkerPool.js:346:12)
>     at /Users/cwanty/dev/volta/client/node_modules/thread-loader/dist/WorkerPool.js:219:29
>     at mapSeries (/Users/cwanty/dev/volta/client/node_modules/neo-async/async.js:3625:14)
>     at CompatResolver.dependenciesOf (/Users/cwanty/dev/volta/client/node_modules/@embroider/compat/src/resolver.js:252:33)
>     at NodeTemplateCompiler.precompile (/Users/cwanty/dev/volta/client/node_modules/@embroider/core/src/template-compiler-common.js:61:42)
>     at precompile (/Users/cwanty/dev/volta/client/node_modules/@embroider/core/src/babel-plugin-inline-hbs-deps.js:23:61)
>     at insertCompiledTemplate (/Users/cwanty/dev/volta/client/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:50:42)
>     at PluginPass.CallExpression (/Users/cwanty/dev/volta/client/node_modules/babel-plugin-ember-template-compilation/src/plugin.js:142:21)
>     at newFn (/Users/cwanty/dev/volta/client/node_modules/@babel/traverse/lib/visitors.js:177:21)
>     at NodePath._call (/Users/cwanty/dev/volta/client/node_modules/@babel/traverse/lib/path/context.js:53:20)
>     at NodePath.call (/Users/cwanty/dev/volta/client/node_modules/@babel/traverse/lib/path/context.js:40:17)
>     at NodePath.visit (/Users/cwanty/dev/volta/client/node_modules/@babel/traverse/lib/path/context.js:100:31)
>     at TraversalContext.visitQueue (/Users/cwanty/dev/volta/client/node_modules/@babel/traverse/lib/context.js:105:16)
> ```

I am also seeing this error when using embroider 1.9 and I have ember-element-helper@0.6.1 installed.  Could the syntax `(-element` be a an error? I am not familiar enough with this. @SergeAstapov @ef4

**Comment by ef4** [comment]
I would first make sure npm/yarn is really giving you the right dependencies. Try running `npx are-my-node-modules-messed-up`.

Then I would try removing `$TMPDIR/embroider` to make sure there's not a cache bug issue.

**Comment by rwwagner90** [comment]
@ef4 I am seeing a similar error here:

`$TMPDIR/embroider/92bbb7/node_modules/.pnpm/ember-animated@1.0.4_pd2l4mfxiv5ycl7j7zliqotjwu/node_modules/ember-animated/dist/components/animated-container.js/animated-container.js: Missing helper: -element in node_modules/.pnpm/ember-animated@1.0.4_pd2l4mfxiv5ycl7j7zliqotjwu/node_modules/ember-animated/dist/components/animated-container.js`
