### ISSUE TITLE
TypeError: yield* (intermediate value)(intermediate value) is not iterable after removing IE11 from transpilation targets

### ISSUE THREAD

**Issue by jelhan** [ember-animation/ember-animated#490]
**Describe the bug**

The following error is thrown in an addon, which uses `ember-animated` after I removed IE11 from `tests/dummy/config/target.js`:

```
TypeError: yield* (intermediate value)(intermediate value) is not iterable
    at runToCompletion (transition-context.js?:formatted:42:11)
    at runToCompletion.next (<anonymous>)
    at AnimatedEach.eval (animated-each.js:199:209)
    at Generator.next (<anonymous>)
    at eval (ember-scheduler.js:27:590)
    at Backburner._run (backburner.js:1052:1)
    at Backburner._join (backburner.js:1028:1)
    at Backburner.join (backburner.js:779:1)
    at join (index.js:91:1)
    at withRunLoop (ember-scheduler.js:27:550)
```

The stack trace points to this line: https://github.com/ember-animation/ember-animated/blob/84a6e17de00601d76b4fe713140220e8d59e5da8/addon/src/-private/transition-context.ts#L12

I'm fully lost to be honest.

**To Reproduce**

I know it is far from being a good reproduction, but I run into this in this PR: https://github.com/marcemira/ember-node-tree/pull/38

**Expected behavior**

It should not throw.

**Additional context**

It might be likely caused by an issue in the consuming addon not in `ember-animated` itself. Any hint to debug it would be very helpful. It's so deep in the internals of ember-animated that I don't know where to start.

**Comment by marcemira** [comment]
It seems to be related to the usage of `yield*` here: https://github.com/ember-animation/ember-animated/blob/master/addon/src/components/animated-each.ts#L742

I seems like `yield*` is better than `yield` for ts and for speed, but also causes this issue, tested using `yield` alone and it does prevents the error. Can't say if it's a babel issue or not (shouldn't this be transpiled?).

Regarding `https://github.com/marcemira/ember-node-tree/pull/38`, it could be possible that we have nested animation contexts causing the issue? We have a potential loop of components doing { animated-forEach -> animated-if -> loopSame }. Still looking into anything that would point me out to a solution
